# -*- coding: utf-8 -*-
"""E_2215016135_Taufan Ali_Praktikum 5.ipnyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1687fl0daNaLFF3-weCWqsl_4Sx9O1oXR
"""

def selectionsort(data) :
  for i in range(len(data)) :
    max_index = i
    for j in range(i+1, len(data)) :
      if data[max_index] < data[j] :
        max_index = j
    print("index key : %d tukar : %d"%(i, max_index))
    print("       iterasi %d"%(i), data)
    data[i], data[max_index] = data[max_index], data[i]

def bubblesort(data):
    n = len(data)
    while True:
        tukar = False
        for i in range(n-1):
            if data[i] < data[i+1]:
                data[i], data[i+1] = data[i+1], data[i]
                tukar = True
                print(f"Tukar {data[i]} dengan {data[i+1]}")
                print("urutan menjadi ", data)
        if not tukar:
            break

a = [3,1,8,4,2]
bubblesort(a)

a = [4,3,5,6,2,78,98]
selectionsort(a)